name: n8n-app-do
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
region: nyc
services:
  - envs:
      - key: WEBHOOK_URL
        scope: RUN_AND_BUILD_TIME
        value: '${_self.PUBLIC_URL}'
      - key: N8N_PUSH_BACKEND
        value: websocket
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: '${n8n-db.DATABASE}'
      - key: DB_POSTGRESDB_HOST
        value: '${n8n-db.HOSTNAME}'
      - key: DB_POSTGRESDB_PORT
        value: '${n8n-db.PORT}'
      - key: DB_POSTGRESDB_USER
        value: '${n8n-db.USERNAME}'
      - key: DB_POSTGRESDB_PASSWORD
        value: '${n8n-db.PASSWORD}'
      - key: DB_POSTGRESDB_SSL_CA
        value: '${n8n-db.CA_CERT}'
    name: web-service
    http_port: 5678
    image:
      registry: n8nio
      registry_type: DOCKER_HUB
      repository: n8n
      tag: latest
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    run_command: n8n
databases:
  - name: n8n-db
    engine: PG
    production: false
